import { pgTable, uuid, text, integer, numeric, boolean, timestamp } from "drizzle-orm/pg-core";

export const hospitalItems = pgTable("hospital_items", {
  id:              uuid("id").primaryKey().defaultRandom(),
  workspaceId:     uuid("workspace_id").notNull(),
  name:            text("name").notNull(),
  genericName:     text("generic_name"),
  itemcode:        text("itemcode"),
  itemtype:        text("itemtype").default("supply"),
  uom:             text("uom").default("piece"),
  manufacturer:    text("manufacturer"),
  supplierId:      text("supplier_id"),
  supplierName:    text("supplier_name"),
  barcode:         text("barcode"),
  storageLocation: text("storage_location"),
  storageType:     text("storage_type"),
  atcCode:         text("atc_code"),
  form:            text("form"),
  strength:        text("strength"),
  description:     text("description"),
  minLevel:        integer("min_level").default(0),
  reorderLevel:    integer("reorder_level").default(10),
  maxLevel:        integer("max_level"),
  unitCost:        numeric("unit_cost", { precision: 10, scale: 2 }),
  sellingPrice:    numeric("selling_price", { precision: 10, scale: 2 }),
  notes:           text("notes"),
  isactive:        boolean("isactive").default(true),
  createdat:       timestamp("createdat").defaultNow(),
  updatedat:       timestamp("updatedat").defaultNow(),
});
